import { chromium } from 'playwright-core';
const SP = process.argv[2]; const b = await chromium.launch();
const mk = async () => { const c = await b.newContext({ viewport: { width: 1280, height: 900 } }); await c.addInitScript(() => localStorage.setItem('starwake-playtest', '1')); const p = await c.newPage(); p.on('pageerror', e => console.log('ERR', e.message)); return p; };
const host = await mk(); await host.goto('http://127.0.0.1:5180'); await host.waitForTimeout(800); await host.click('#launch-button');
const code = await host.waitForFunction(() => document.querySelector('#lobby-screen.active') && window.__starwake.state.code, null, { timeout: 15000 }).then(h => h.jsonValue());
const guest = await mk(); await guest.goto(`http://127.0.0.1:5180/?room=${code}&from=HOST`); await guest.waitForTimeout(800); await guest.click('#launch-skip');
await guest.waitForFunction((c) => document.querySelector('#lobby-screen.active') && window.__starwake.state.code === c, code, { timeout: 15000 });
await host.fill('#party-idea', 'candy volcano'); await host.click('#party-idea-form button');
await guest.fill('#party-idea', 'haunted space station'); await guest.click('#party-idea-form button');
await host.waitForFunction(() => document.querySelectorAll('#party-ideas .party-chip').length >= 3, null, { timeout: 12000 });
const chips = await host.evaluate(() => [...document.querySelectorAll('#party-ideas .party-chip')].map(c => c.innerText));
console.log('host sees', chips, 'button:', await host.textContent('#party-fuse'));
await host.locator('#party-forge').scrollIntoViewIfNeeded(); await host.screenshot({ path: `${SP}/party-before.png` });
await host.click('#party-fuse');
const hostCourse = await host.waitForFunction(() => /NOW RACING/.test(document.querySelector('#party-status').innerText) && window.__starwake.state.room.courseId, null, { timeout: 30000 }).then(h => h.jsonValue()).catch(() => null);
const guestCourse = await guest.waitForFunction((id) => window.__starwake.state.room?.courseId === id && window.__starwake.state.room.coursePrompt, hostCourse, { timeout: 15000 }).then(h => h.jsonValue()).catch(() => null);
console.log('host course', hostCourse, '| guest sees prompt:', guestCourse);
console.log('guest status:', await guest.textContent('#party-status'));
await host.screenshot({ path: `${SP}/party-after.png` });
await b.close();
